version: '3.8'
services:
  mysql-db:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jwt-network

    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=root", "--execute=SHOW DATABASES;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  jwt-service:
    container_name: jwt-service
    build: ../
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/jwt_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
    networks:
      - jwt-network
    volumes:
      - app-logs:/app/logs
  redis:
    image: redis:7
    container_name: redis-cli
    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - jwt-network

networks:
  jwt-network:
    name: jwt-network

volumes:
  mysql-data:
  app-logs: