server:
  port: 8081

spring:
  application:
    name: jwt-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: ${SPRING_REDIS_HOST}
    port: 6379
jwt:
  secret: ${JWT_SECRET_KEY:dmVyeSBsb25nIHRleHQgdXNlZCBmb3IgZW5jb25kaW5nIGp3dA==}
  access-token-expiration-ms: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always